version: 2
jobs:
  build:
    working_directory: ~/arsduo/commonplace-feeds
    docker:
      - image: arsduo/elm-elixir-starter
        environment:
          PG_USER: ubuntu
          PD_DB: circle_test
          PG_PASS: ""
      - image: postgres:9.6.2
        environment:
          POSTGRES_USER: ubuntu
          POSTGRES_DB: circle_test
          POSTGRES_PASSWORD: ""
    environment:
      - PHOENIX_SECRET_KEY_BASE: 26b18785843693e1a3e81d82f92223c37844a2ab0f042a87e87481e75bd55a7a
      - GUARDIAN_SECRET_KEY: f4dc9536a7bee266b05b1910fc85608288e044c649761b50e9d545445f10e1d6
    steps:
    - checkout
    - run: mix deps.get
    - run: mix test
    - run: MIX_ENV=test mix credo
    - run: yarn format-elixir
    - run: yarn lint
